### ISSUE TITLE
Ray tracing info

### ISSUE THREAD

**Issue by makew0rld** [nanochess/cubicDoom#2]
Hello. This project is super cool! I'm interested in doing something similar with ray tracing in a kind of assembly, and I was wondering if you could explain the ray tracing you did, or point me to any free resources that can explain it at a low level. I know there are some ray tracing guides online, but they all start with defining floating point vector structs and stuff, and so I'm not sure how to make the jump to the kind of stuff you're doing here.

Specifically I'm looking at this code: https://github.com/nanochess/cubicDoom/blob/5e88760a968c6f9a9088e515613b24abc0131d46/doom.asm#L152-L207

Thanks!

**Comment by nanochess** [comment]
It is basically getting cos and sin as 8.8 fixed-point values, and add these to the start position (the current position of player), repeating the addition (it is doing a line over the map), and at same time remove the fraction and compare with the X,Y map coordinates to check if passing over a wall.
